### ISSUE TITLE
Center data before doing PCA using SVD

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_release#34]
https://github.com/LHCfitNikhef/smefit_release/blob/3d2b106d0c3d582440b58f902e450e61cc98e8b3/src/smefit/analyze/pca.py#L144

When computing the principle components using singular value decomposition (SVD), one should always centralise the data first, see also this thread [here](https://stats.stackexchange.com/questions/189822/how-does-centering-make-a-difference-in-pca-for-svd-and-eigen-decomposition) and also [here](https://stats.stackexchange.com/questions/22329/how-does-centering-the-data-get-rid-of-the-intercept-in-regression-and-pca). 

One can either compute the principle components as the eigenvectors of the covariance matrix, which is insensitive to the mean of the data since it gets subtracted, or using SVD, but here the decomposition is not invariant under translations.

**Comment by giacomomagni** [comment]
Hi @jacoterh, thanks for bringing this up. 
Yes indeed the old code was doing this way, but the paper (both smefit and ATLAS) didn't mention anything about it so I didn't implemented it here... 

The fix should be:
```
 X_centered = X - X.mean(axis=0)
 _, W, Vt = np.linalg.svd(X_centered)
 ```
Here we are doing PCA on LinearCorr/covmat so this might have an effect.
