### ISSUE TITLE
Order of coefficients gets reshuffled

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_release#38]
Hi, 

Just to keep track, we noticed that on numpy=1.23.1 and pandas=1.4.4 the assignment of the numpy array params to temp_coeffs shows random behaviour, i.e. the order did not get respected.

https://github.com/LHCfitNikhef/smefit_release/blob/a2c6b2e81e9c8e13afc485cbe9979a6b1fa6e0a3/src/smefit/analyze/pca.py#L187

Updating to pandas=1.5.2 fixed this issue.

**Comment by tgiani** [comment]
Hi @jacoterh, can you please try to install the code from the branch `reproducible_conda_env` using the new installation script and see if with that everything works for you?

**Comment by tgiani** [comment]
the new installation script will create a new conda environment with smefit and its dependecies installed in it
