### ISSUE TITLE
UV parser: key not found for constrained coefficients

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_release#45]
Hi Giacomo,

This is merely to keep track of what I found while working with the UV model parser. I noticed that [this](https://github.com/LHCfitNikhef/smefit_release/blob/fe1ca808b4a66486044e44a16c82eeb124933e11/runcards/uv_models/write_runcards.py#L74) line checks for the presence of constraints, but it cannot find the key `value` for some of the UV models. For instance this one [here](https://github.com/LHCfitNikhef/smefit_release/blob/fe1ca808b4a66486044e44a16c82eeb124933e11/runcards/uv_models/WC_scan/Granada/dict_WC_scan_Coll_Granada_Mod_44_Mass_1_Tree.yaml#L19). 

We can have a look tomorrow maybe?

**Comment by giacomomagni** [comment]
oh yes I missed a `try` statement in the parser...
