### ISSUE TITLE
Bug in plot_posteriors

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_release#46]
Hi Giacomo,

The following checks whether `disjointed_lists` is `None`, but this will always fail because of the line [here](https://github.com/LHCfitNikhef/smefit_release/blob/775df86c7a6499b70fda5e308b089456d8e03927/src/smefit/analyze/report.py#L263)

https://github.com/LHCfitNikhef/smefit_release/blob/775df86c7a6499b70fda5e308b089456d8e03927/src/smefit/analyze/coefficients_utils.py#L340

It is probably a quick fix.

Thanks!

**Comment by giacomomagni** [comment]
I think I recently fix this on the `smefit_uv` branch: 
https://github.com/LHCfitNikhef/smefit_release/blob/4f1b7c988e4f20caebfa59736fdf6b46e196dec7/src/smefit/analyze/coefficients_utils.py#L340

is this correct?

**Comment by jacoterh** [comment]
Yes that fixes it, I will open a separate branch and link a PR to main!

**Comment by giacomomagni** [comment]
you can commit directly to main thanks

**Comment by jacoterh** [comment]
Fixed in defee38
