### ISSUE TITLE
Contour plot additions

### ISSUE THREAD

**Issue by Brognor** [LHCfitNikhef/smefit_release#48]
Dear all,

 I am using SMEFIT to fit new physics parameters using quadratic correction. At the moment I have seen that the report card contains the possibility to plot contour plots for parameters couple. 

- I would like to have in the same plot the 68% and 95% contour, but at the moment it does not seem to me that this is possible. Would it be possible to implement this feature?

-In quadratic fit no mark is placed in the plot for the best value(s) of the fitted parameters. In quadratic fit I expect more than one optimal position, wouldn't be possible to put a marker for each of them?

**Comment by giacomomagni** [comment]
Hi @Brognor, thanks for using our code. 
I think we can fix both points and add such feature to the plots (the marker for sure ... ). 
Am I correct @jacoterh ?

**Comment by jacoterh** [comment]
Yes, we can definitely add this in the next iteration!

**Comment by giacomomagni** [comment]
Hi @Brognor I've opened a PR in which this feature is implemented. 
Please let us know if this works and if there are other fixes that you might need.
To display both 68% and 95% you can use in the report runcard:

```
  contours_2d:
    confidence_level: [68, 95]
    dofs_show: ["OQQ1", "OQQ8"]
```

**Comment by Brognor** [comment]
Dear Giacomo,
now I can visualize both contours, thank you so much.

- Would it be possible to have them in different styles (maybe a continuos and a dashed line), and to put this in the legend? At the present moment, I only see in the legend the different colours associated to each fit.

- I cannot visualize the markers for the best prediction(s) (having a quad fit I expect more than one) for fittedparameters, is it possible to place them? 

Many thanks again

**Comment by giacomomagni** [comment]
Hi @Brognor

> * Would it be possible to have them in different styles (maybe a continuos and a dashed line), and to put this in the legend? At the present moment, I only see in the legend the different colours associated to each fit.

sure this is possible, but to avoid 100 iterations maybe we can do it together or you can make a proposal directly on that branch PR, otherwise we risk to waste time both of us. 

> * I cannot visualize the markers for the best prediction(s) (having a quad fit I expect more than one) for fittedparameters, is it possible to place them?
> 

This instead should be quite easy to add as done for the linear case, also for `kde`.
