### ISSUE TITLE
Ill defined relative systematic for zero central value

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_release#52]
Hi,

The following line throws an uncaught exception in case the central value is zero, which is the case for instance in the CMS_SSinc_RunII dataset. The fit goes on with inf in the multiplicative systematic array.

https://github.com/LHCfitNikhef/smefit_release/blob/85a6e9af62ba449b8d85161d188a3a266fb01b24/src/smefit/loader.py#L154

But it's not a problem in case the corresponding systematic is additive, it gets filtered out, but it would be nice to have some kind of fix anyway.

**Comment by giacomomagni** [comment]
This can be done... however I wonder how can a central value be exactly 0 ?

**Comment by jacoterh** [comment]
Some of the CMS RunII signal strengths have been restricted to nonnegative values and this results in a best fit value of exactly zero apparently, see page 16 in https://arxiv.org/pdf/1809.10733.pdf: 

"In the case of WH, ZH, and ttH production with H → ZZ decay, as well as ZH production with H → γγ decay, the background contamination is sufficiently low so that a negative signal strength can result in an overall negative event yield. Therefore, these signal strengths are restricted to nonnegative values"

![image](https://github.com/LHCfitNikhef/smefit_release/assets/54140851/3efc54f7-b945-4d6a-901e-1d804a377b68)

The gaussian approximation is not valid for these datapoints...

**Comment by giacomomagni** [comment]
Okay, if this is the case I think we have a problem with these points. When we symmetries the error the central value should also shift. 
So if the CMS result, with asymmetric error is 0, we should not have 0 in out tables... 
Am I correct ? @tgiani  
Maybe we should remove those points @juanrojochacon ?

**Comment by juanrojochacon** [comment]
I would say that for such points a Gaussian likelihood is not appropriate, and hence should be discarded from the analysis

**Comment by giacomomagni** [comment]
shall I close @jacoterh ?
